 #include "stdio.h"
 #include "conio.h"

 void main (){

 clrscr();

 float area, radius, pie=3.14;
 printf("\n\nCalculating the Area of a Circle...");
 printf("\n\n\t\tãrý");

 printf("\n\nã is constant and equal to = 3.14");


 printf("\n\n\n\tEnter Radius = ");
 scanf("%f",&radius);

 area=pie*(radius*radius);

 printf("\n\n\n        => The area of the circle is %.1f meter",area);

 getch();

 }